# Generated by Django 3.1 on 2020-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAPI_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
